In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Data_for_UCI_named.csv')

In [3]:
df

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2.930406,9.487627,2.376523,6.187797,3.343416,-0.658054,-1.449106,-1.236256,0.601709,0.779642,0.813512,0.608385,0.023892,unstable
9996,3.392299,1.274827,2.954947,6.894759,4.349512,-1.663661,-0.952437,-1.733414,0.502079,0.567242,0.285880,0.366120,-0.025803,stable
9997,2.364034,2.842030,8.776391,1.008906,4.299976,-1.380719,-0.943884,-1.975373,0.487838,0.986505,0.149286,0.145984,-0.031810,stable
9998,9.631511,3.994398,2.757071,7.821347,2.514755,-0.966330,-0.649915,-0.898510,0.365246,0.587558,0.889118,0.818391,0.037789,unstable
9999,6.530527,6.781790,4.349695,8.673138,3.492807,-1.390285,-1.532193,-0.570329,0.073056,0.505441,0.378761,0.942631,0.045263,unstable

In [4]:
df = df.drop(columns=['stab'])

In [5]:
df

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,unstable
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2.930406,9.487627,2.376523,6.187797,3.343416,-0.658054,-1.449106,-1.236256,0.601709,0.779642,0.813512,0.608385,unstable
9996,3.392299,1.274827,2.954947,6.894759,4.349512,-1.663661,-0.952437,-1.733414,0.502079,0.567242,0.285880,0.366120,stable
9997,2.364034,2.842030,8.776391,1.008906,4.299976,-1.380719,-0.943884,-1.975373,0.487838,0.986505,0.149286,0.145984,stable
9998,9.631511,3.994398,2.757071,7.821347,2.514755,-0.966330,-0.649915,-0.898510,0.365246,0.587558,0.889118,0.818391,unstable
9999,6.530527,6.781790,4.349695,8.673138,3.492807,-1.390285,-1.532193,-0.570329,0.073056,0.505441,0.378761,0.942631,unstable

In [6]:
df[ 'stabf' ].value_counts() #check distribution of target variable

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [7]:
df.isna().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stabf    0
dtype: int64

In [8]:
df_unstable = df[df.stabf== 'unstable' ].sample( 3620 )

In [9]:
df_unstable

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stabf
9616,7.084135,8.578033,7.763756,2.618585,4.261561,-1.294133,-1.596176,-1.371251,0.603369,0.684889,0.745613,0.814873,unstable
4438,8.423846,9.879951,0.883542,4.484222,3.199318,-1.318114,-1.130723,-0.750480,0.803411,0.276484,0.489234,0.542416,unstable
8135,7.933110,3.155478,7.292384,6.203915,3.839754,-1.517137,-0.932695,-1.389922,0.823026,0.675045,0.839612,0.589301,unstable
2257,9.041926,0.745115,9.110084,4.670637,4.357939,-1.182647,-1.703009,-1.472283,0.903155,0.348442,0.464309,0.328960,unstable
1734,9.148925,1.178601,6.317474,5.781026,5.209885,-1.935424,-1.631543,-1.642919,0.722817,0.652926,0.871484,0.988220,unstable
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9945,4.334827,3.226723,9.757393,6.584116,4.139547,-1.481436,-1.731488,-0.926623,0.832177,0.165210,0.960831,0.993508,unstable
7463,5.833242,1.518674,7.886629,7.619417,4.171626,-1.650587,-1.494063,-1.026976,0.096676,0.904322,0.708378,0.464334,unstable
4978,4.198725,7.398983,7.680383,3.302607,3.722842,-1.616337,-1.179534,-0.926971,0.620239,0.126477,0.364722,0.557132,unstable
216,7.935976,9.197423,6.005967,2.948855,3.264267,-0.920200,-0.719697,-1.624371,0.697070,0.749622,0.303727,0.235419,unstable
8004,7.214450,2.265906,3.889059,9.012663,3.675266,-0.722557,-1.249246,-1.703463,0.837425,0.599088,0.975245,0.772472,unstable

In [10]:
df_stable = df[df.stabf== 'stable' ]

In [11]:
df_stable

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stabf
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,stable
5,6.999209,9.109247,3.784066,4.267788,4.429669,-1.857139,-0.670397,-1.902133,0.261793,0.077930,0.542884,0.469931,stable
8,4.689852,4.007747,1.478573,3.733787,4.041300,-1.410344,-1.238204,-1.392751,0.269708,0.250364,0.164941,0.482439,stable
10,5.930110,6.730873,6.245138,0.533288,2.327092,-0.702501,-1.116920,-0.507671,0.239816,0.563110,0.164461,0.753701,stable
12,1.616787,2.939228,0.819791,4.191804,3.752282,-1.484885,-1.280581,-0.986816,0.899698,0.866546,0.303921,0.077610,stable
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9980,4.141337,1.112868,8.400888,1.869624,3.671563,-0.699052,-1.513896,-1.458615,0.081811,0.094963,0.662959,0.169682,stable
9983,1.482214,3.121273,5.220920,1.609288,4.394557,-1.924542,-0.881996,-1.588019,0.097309,0.096599,0.383334,0.988509,stable
9984,2.501787,3.087194,7.493896,2.177944,3.817471,-0.958986,-1.044281,-1.814205,0.503049,0.107808,0.534358,0.357840,stable
9996,3.392299,1.274827,2.954947,6.894759,4.349512,-1.663661,-0.952437,-1.733414,0.502079,0.567242,0.285880,0.366120,stable
9997,2.364034,2.842030,8.776391,1.008906,4.299976,-1.380719,-0.943884,-1.975373,0.487838,0.986505,0.149286,0.145984,stable

In [12]:
data_df = df_stable.append(df_unstable)

In [13]:
data_df

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stabf
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,stable
5,6.999209,9.109247,3.784066,4.267788,4.429669,-1.857139,-0.670397,-1.902133,0.261793,0.077930,0.542884,0.469931,stable
8,4.689852,4.007747,1.478573,3.733787,4.041300,-1.410344,-1.238204,-1.392751,0.269708,0.250364,0.164941,0.482439,stable
10,5.930110,6.730873,6.245138,0.533288,2.327092,-0.702501,-1.116920,-0.507671,0.239816,0.563110,0.164461,0.753701,stable
12,1.616787,2.939228,0.819791,4.191804,3.752282,-1.484885,-1.280581,-0.986816,0.899698,0.866546,0.303921,0.077610,stable
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9945,4.334827,3.226723,9.757393,6.584116,4.139547,-1.481436,-1.731488,-0.926623,0.832177,0.165210,0.960831,0.993508,unstable
7463,5.833242,1.518674,7.886629,7.619417,4.171626,-1.650587,-1.494063,-1.026976,0.096676,0.904322,0.708378,0.464334,unstable
4978,4.198725,7.398983,7.680383,3.302607,3.722842,-1.616337,-1.179534,-0.926971,0.620239,0.126477,0.364722,0.557132,unstable
216,7.935976,9.197423,6.005967,2.948855,3.264267,-0.920200,-0.719697,-1.624371,0.697070,0.749622,0.303727,0.235419,unstable
8004,7.214450,2.265906,3.889059,9.012663,3.675266,-0.722557,-1.249246,-1.703463,0.837425,0.599088,0.975245,0.772472,unstable

In [14]:
import sklearn.utils

In [15]:
data_df = sklearn.utils.shuffle(data_df)

In [16]:
data_df

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stabf
2674,3.454660,7.099692,5.449574,8.406364,3.434148,-0.531532,-1.006755,-1.895861,0.527738,0.334113,0.294273,0.347974,unstable
6240,7.648044,7.183136,6.957423,0.984254,2.876449,-0.518137,-1.701176,-0.657136,0.323630,0.701277,0.141150,0.717013,stable
5326,2.352762,1.495592,8.791875,4.286369,4.996334,-1.804319,-1.823887,-1.368128,0.256552,0.228885,0.664014,0.923061,unstable
6260,4.449887,5.226421,4.290912,2.192644,4.332402,-1.684963,-0.772870,-1.874570,0.066088,0.447714,0.478212,0.683828,stable
386,8.013824,2.947677,3.433458,1.861393,3.510187,-1.475764,-1.295595,-0.738828,0.161018,0.256581,0.136364,0.509919,stable
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2038,9.729724,1.393835,4.971937,5.947571,3.786717,-1.570609,-1.009517,-1.206590,0.342992,0.264173,0.332000,0.319357,stable
9243,9.064642,2.662566,6.785644,0.878797,4.143776,-1.254777,-1.319434,-1.569566,0.246974,0.259688,0.781817,0.357305,stable
2669,2.834818,7.846789,2.509574,4.563667,3.598126,-0.724912,-0.990924,-1.882290,0.672901,0.113269,0.417650,0.372884,stable
9941,3.735131,3.389440,8.474883,1.524800,3.348870,-1.280650,-0.838186,-1.230033,0.193190,0.608711,0.400194,0.850888,stable
2709,2.588112,7.982194,5.911554,2.105470,4.531460,-1.951851,-1.967099,-0.612510,0.464405,0.870957,0.680696,0.415866,unstable

In [17]:
data_df = data_df.reset_index(drop= True )

In [18]:
data_df

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stabf
0,3.454660,7.099692,5.449574,8.406364,3.434148,-0.531532,-1.006755,-1.895861,0.527738,0.334113,0.294273,0.347974,unstable
1,7.648044,7.183136,6.957423,0.984254,2.876449,-0.518137,-1.701176,-0.657136,0.323630,0.701277,0.141150,0.717013,stable
2,2.352762,1.495592,8.791875,4.286369,4.996334,-1.804319,-1.823887,-1.368128,0.256552,0.228885,0.664014,0.923061,unstable
3,4.449887,5.226421,4.290912,2.192644,4.332402,-1.684963,-0.772870,-1.874570,0.066088,0.447714,0.478212,0.683828,stable
4,8.013824,2.947677,3.433458,1.861393,3.510187,-1.475764,-1.295595,-0.738828,0.161018,0.256581,0.136364,0.509919,stable
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7235,9.729724,1.393835,4.971937,5.947571,3.786717,-1.570609,-1.009517,-1.206590,0.342992,0.264173,0.332000,0.319357,stable
7236,9.064642,2.662566,6.785644,0.878797,4.143776,-1.254777,-1.319434,-1.569566,0.246974,0.259688,0.781817,0.357305,stable
7237,2.834818,7.846789,2.509574,4.563667,3.598126,-0.724912,-0.990924,-1.882290,0.672901,0.113269,0.417650,0.372884,stable
7238,3.735131,3.389440,8.474883,1.524800,3.348870,-1.280650,-0.838186,-1.230033,0.193190,0.608711,0.400194,0.850888,stable
7239,2.588112,7.982194,5.911554,2.105470,4.531460,-1.951851,-1.967099,-0.612510,0.464405,0.870957,0.680696,0.415866,unstable

In [19]:
data_df.shape

(7240, 13)

In [20]:
data_df.stabf.value_counts()

stable      3620
unstable    3620
Name: stabf, dtype: int64

In [21]:
X = data_df.drop(columns= 'stabf' )
y = data_df[ 'stabf' ]

In [22]:
#split the data into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size= 0.2 , random_state= 1 )
y_train.value_counts()

stable      2924
unstable    2868
Name: stabf, dtype: int64

In [23]:
import imblearn
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state= 1 )
x_train_balanced, y_balanced = smote.fit_sample(x_train, y_train)

In [24]:
y_balanced.value_counts()

stable      2924
unstable    2924
Name: stabf, dtype: int64

In [25]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [26]:
normalised_train_df = scaler.fit_transform(x_train_balanced)

In [27]:
normalised_train_df = pd.DataFrame(normalised_train_df, columns=x_train_balanced.columns)

In [28]:
normalised_train_df

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4
0,0.343538,0.967283,0.142698,0.446019,0.233701,0.946775,0.942491,0.388674,0.168644,0.086132,0.695181,0.379560
1,0.185081,0.736247,0.820843,0.598076,0.596118,0.258720,0.754355,0.230082,0.287710,0.005235,0.928208,0.658602
2,0.231826,0.755288,0.370814,0.972975,0.609353,0.605644,0.479979,0.119748,0.879839,0.659676,0.785623,0.563670
3,0.909556,0.599929,0.691597,0.473522,0.694073,0.426464,0.330929,0.206083,0.416819,0.500296,0.891271,0.196166
4,0.848987,0.434982,0.115029,0.153702,0.786216,0.195143,0.462623,0.042617,0.100563,0.894323,0.648508,0.152792
...,...,...,...,...,...,...,...,...,...,...,...,...
5843,0.483361,0.968523,0.536613,0.981662,0.655417,0.433581,0.294663,0.345603,0.138071,0.554892,0.588905,0.285106
5844,0.543499,0.873473,0.321039,0.612460,0.385196,0.526951,0.931820,0.386614,0.476909,0.269613,0.012243,0.662979
5845,0.914056,0.561017,0.839994,0.733354,0.627080,0.171024,0.708953,0.274774,0.210750,0.959003,0.614080,0.551541
5846,0.395361,0.841623,0.641040,0.998855,0.607951,0.840140,0.284239,0.084998,0.621348,0.764139,0.904711,0.385905
5847,0.302196,0.627180,0.108227,0.528871,0.281654,0.658095,0.730319,0.752607,0.766019,0.315505,0.616589,0.771527

In [29]:
x_test = x_test.reset_index(drop= True )

In [30]:
x_test

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4
0,4.960137,5.194127,5.830009,9.521613,4.338979,-1.896481,-1.274290,-1.168208,0.087920,0.169011,0.354281,0.090019
1,7.286377,8.673849,2.580084,5.388073,3.435488,-1.832430,-0.846343,-0.756716,0.126148,0.676419,0.159271,0.091530
2,6.297792,7.755648,3.759722,8.158005,4.101561,-1.821891,-0.998809,-1.280861,0.538787,0.336378,0.823630,0.892655
3,5.671346,2.910891,0.933075,5.402689,4.033685,-1.764620,-1.571622,-0.697443,0.218617,0.072572,0.329413,0.702260
4,5.056023,6.287010,5.766039,3.053450,3.989938,-1.308706,-1.749219,-0.932013,0.218506,0.263111,0.586366,0.389042
...,...,...,...,...,...,...,...,...,...,...,...,...
1443,4.889106,4.393696,9.260098,3.835306,3.220454,-1.336938,-1.343121,-0.540395,0.696167,0.810251,0.512402,0.209671
1444,3.885980,8.207832,2.973996,5.344588,4.030184,-0.583405,-1.501143,-1.945636,0.732962,0.703054,0.323172,0.758142
1445,7.893091,6.669702,9.428470,1.969979,3.464060,-1.072148,-0.721894,-1.670018,0.642595,0.930616,0.592973,0.340349
1446,3.052342,8.140272,5.904712,3.246251,4.254785,-1.910327,-1.672108,-0.672350,0.723031,0.599791,0.461665,0.739940
1447,7.809068,8.327915,6.856530,9.480309,3.749968,-1.633765,-0.743731,-1.372472,0.734441,0.462540,0.228090,0.248098

In [31]:
normalised_test_df = scaler.transform(x_test)

In [32]:
normalised_test_df

array([[0.4695556 , 0.49419996, 0.56112889, ..., 0.12516926, 0.32027561,
        0.04210192],
       [0.71450176, 0.86055785, 0.21887916, ..., 0.65941571, 0.114945  ,
        0.0436924 ],
       [0.61040674, 0.7638863 , 0.34310689, ..., 0.30138849, 0.81446453,
        0.88711207],
       ...,
       [0.77838697, 0.64955397, 0.94008307, ..., 0.92705857, 0.57160028,
        0.30564746],
       [0.26867045, 0.80438097, 0.56899589, ..., 0.57873497, 0.43334272,
        0.72633467],
       [0.76953951, 0.82413667, 0.66923189, ..., 0.43422433, 0.18740612,
        0.20852619]])

In [33]:
normalised_test_df = pd.DataFrame(normalised_test_df, columns=x_test.columns)

In [34]:
normalised_test_df

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4
0,0.469556,0.494200,0.561129,0.949750,0.643741,0.068857,0.483881,0.554441,0.039915,0.125169,0.320276,0.042102
1,0.714502,0.860558,0.218879,0.514569,0.432735,0.111568,0.769245,0.828833,0.080163,0.659416,0.114945,0.043692
2,0.610407,0.763886,0.343107,0.806188,0.588293,0.118596,0.667577,0.479321,0.514613,0.301388,0.814465,0.887112
3,0.544444,0.253813,0.045433,0.516108,0.572441,0.156786,0.285614,0.868357,0.177520,0.023629,0.294092,0.686666
4,0.479652,0.609263,0.554392,0.268779,0.562224,0.460803,0.167189,0.711940,0.177403,0.224247,0.564644,0.356911
...,...,...,...,...,...,...,...,...,...,...,...,...
1443,0.462076,0.409928,0.922352,0.351093,0.382515,0.441977,0.437983,0.973080,0.680311,0.800327,0.486765,0.168071
1444,0.356450,0.811494,0.260362,0.509991,0.571624,0.944455,0.332611,0.036035,0.719051,0.687460,0.287520,0.745498
1445,0.778387,0.649554,0.940083,0.154710,0.439408,0.618547,0.852230,0.219823,0.623908,0.927059,0.571600,0.305647
1446,0.268670,0.804381,0.568996,0.289077,0.624078,0.059624,0.218608,0.885090,0.708596,0.578735,0.433343,0.726335
1447,0.769540,0.824137,0.669232,0.945401,0.506181,0.244044,0.837668,0.418233,0.720608,0.434224,0.187406,0.208526

In [35]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

In [36]:
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

In [37]:
#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_train_balanced,y_balanced)

RandomForestClassifier()

In [38]:
y_pred=clf.predict(x_test)

In [39]:
print('Predicted Class: ' + y_pred[0])

Predicted Class: stable

In [40]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

In [41]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9191988950276243

In [45]:
# evaluate extra trees algorithm for classification
from numpy import mean
from numpy import std
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import ExtraTreesClassifier

In [46]:
# define the model
ETCmodel = ExtraTreesClassifier()

In [47]:
# evaluate the model
ETCcv = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=1)
n_scores = cross_val_score(ETCmodel, x_train_balanced, y_balanced, scoring='accuracy', cv=ETCcv, n_jobs=-1, error_score='raise')
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Accuracy: 0.922 (0.010)

In [48]:
# fit the model on the whole dataset
ETCmodel.fit(x_train_balanced, y_balanced)
# make a single prediction
row = x_test
yhat = ETCmodel.predict(row)
print('Predicted Class: ' + yhat[0])

Predicted Class: stable

In [56]:
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
ETC = ExtraTreesClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
ETC.fit(x_train_balanced,y_balanced)

ExtraTreesClassifier()

In [57]:
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=-1,
            oob_score=False, random_state=None, verbose=1,
            warm_start=False)

RandomForestClassifier(n_estimators=500, n_jobs=-1, verbose=1)

In [62]:
import pandas as pd
feature_imp = pd.Series(clf.feature_importances_,index=normalised_train_df.columns).sort_values(ascending=False)
feature_imp

tau2    0.129648
tau1    0.128584
tau4    0.123538
tau3    0.113385
g2      0.102382
g3      0.098318
g4      0.095323
g1      0.091746
p4      0.030150
p3      0.029658
p2      0.028746
p1      0.028522
dtype: float64

In [61]:
print(normalised_train_df.columns)

Index(['tau1', 'tau2', 'tau3', 'tau4', 'p1', 'p2', 'p3', 'p4', 'g1', 'g2',
       'g3', 'g4'],
      dtype='object')

In [52]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
rf = ExtraTreesClassifier()
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 10, cv = 5, verbose=1, random_state=1, n_jobs = -1)
rf_random.fit(x_train_balanced, y_balanced)
rf_random.best_params_

Fitting 5 folds for each of 10 candidates, totalling 50 fits

{'n_estimators': 600,
 'min_samples_split': 5,
 'min_samples_leaf': 2,
 'max_features': 'auto',
 'max_depth': 80,
 'bootstrap': False}

In [53]:
# xgboost for classification
from numpy import asarray
from numpy import mean
from numpy import std
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from matplotlib import pyplot

In [54]:
# evaluate the model
XGBmodel = XGBClassifier()
XGBcv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(XGBmodel, x_train_balanced, y_balanced, scoring='accuracy', cv=XGBcv, n_jobs=-1, error_score='raise')
print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Accuracy: 0.938 (0.010)

In [55]:
# fit the model on the whole dataset
XGBmodel = XGBClassifier()
XGBmodel.fit(x_train_balanced, y_balanced)
# make a single prediction
row = x_test
yhat = XGBmodel.predict(row)
print('Prediction: ' + yhat[0])

[21:27:12] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

C:\ProgramData\Anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

Prediction: stable

In [66]:
# lightgbm for classification
from numpy import mean
from numpy import std
from lightgbm import LGBMClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from matplotlib import pyplot

In [67]:
# evaluate the model
LGBmodel = LGBMClassifier()
LGBcv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(LGBmodel, X, y, scoring='accuracy', cv=LGBcv, n_jobs=-1, error_score='raise')
print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Accuracy: 0.941 (0.009)

In [68]:
# fit the model on the whole dataset
LGBmodel = LGBMClassifier()
LGBmodel.fit(x_train_balanced, y_balanced)
# make a single prediction
row = x_test
yhat = LGBmodel.predict(row)
print('Prediction: ' + yhat[0])

Prediction: stable